### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by eliaspekkala** [sousandrei/firesquid#16]
Hey, cool project!

I tried the application and had some issues with permissions.

The first issue is that I couldn't download `Linux Kernel 5.9-rc2` that is listed in the Asset section of the README.

The error was: 
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>
```

So I grabbed the kernel and rootfs from [Getting Started with Firecracker](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#running-firecracker) instead (and Firecracker v0.23.0).

Then I started the app with `cargo run` and sent this request:
```
~/.../firesquid >>> curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"vm_name":"test"}' \      
  http://localhost:3000          
```

The response was:
```
{"success":true}%
```

But this was printed to the console:
```
thread 'tokio-runtime-worker' panicked at 'Failed to spawn vm child process: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/vm/child.rs:29:10
```

Any idea why I got a permission denied error?

I would be happy to provide more information if needed.

**Comment by sousandrei** [comment]
Heya! Thanks for the interest haha

The download permission thing was my bad, should be fixed now :D (forgot to check a box in GCP)

The execution permission I think is related to the firecracker binary not being executable
Try executing 
```
chmod +x firecracker
```

I'll most certainly include this in the docs that I'm working on haha 👀

**Comment by eliaspekkala** [comment]
Thank you, the issues are now solved :+1:
